const path = require("node:path");
const assert = require("node:assert/strict");
const { randomUUID } = require("node:crypto");

require("dotenv").config({
  path: path.resolve(__dirname, "../.env"),
});

// Load the JavaScript generated by npm run build.
const {
  generateOtp,
  hashSignupOtp,
  matchesSignupOtp,
} = require("../dist/lib/otp");

const signupId = randomUUID();
const email = "otp-test@example.com";
const otp = generateOtp();
const storedHash = hashSignupOtp(signupId, email, otp);

// Our chosen generator always returns six digits without a leading zero.
assert.equal(typeof otp, "string");
assert.match(otp, /^[1-9]\d{5}$/);
assert.match(storedHash, /^[a-f0-9]{64}$/);

// The correct code must match.
assert.equal(
  matchesSignupOtp(signupId, email, otp, storedHash),
  true
);

// Choose a valid six-digit code that differs from the generated code.
const wrongOtp = otp === "123456" ? "654321" : "123456";

assert.equal(
  matchesSignupOtp(signupId, email, wrongOtp, storedHash),
  false
);

// The same code must not match a different signup or email.
assert.equal(
  matchesSignupOtp(randomUUID(), email, otp, storedHash),
  false
);

assert.equal(
  matchesSignupOtp(signupId, "other@example.com", otp, storedHash),
  false
);

// Invalid input formats must be rejected.
assert.equal(
  matchesSignupOtp(signupId, email, "12abc", storedHash),
  false
);

assert.equal(
  matchesSignupOtp(signupId, email, otp, "invalid-hash"),
  false
);

console.log("All OTP helper checks passed.");